# General
email: eu@douglasmedeiros.dev
source: .
destination: ./public
baseurl: ""
personal_url: https://douglasmedeiros.dev
srcurl: ""
lang: pt-BR
locale: pt_BR
google_analytics: "G-9XPJXZ5YET"
published: true

###### SEO (jekyll-seo-tag)
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: "Blog Douglas Medeiros"
author: Douglas Medeiros
description: Blog pessoal para compartilhar conhecimento sobre desenvolvimento de software, tecnologia e carreira.
tagline: Software, Tecnologia e Carreira
url: https://blog.douglasmedeiros.dev
image: /assets/posts/notebook-cabos-e-cafe.jpeg
social:
  name: Douglas Medeiros
  links:
    - https://www.instagram.com/douglasmedeiros.dev/
    - https://bsky.app/profile/douglasmedeiros.dev
    - https://github.com/medeirosinacio
    - https://www.linkedin.com/in/medeirosinacio/
type: blog
keywords: Douglas Medeiros, Douglas, Medeiros, Software, Engenheiro, PicPay, Blog, Tutorial, Desenvolvimento

# Blog Paginator configuration
paginate: 5
paginate_path: "/pagina/:num"


# Site Paths
post_path: /assets/images/posts/
icon_path: /assets/icons/
image_path: /assets/images/
css_path: /assets/css/
js_path: /assets/scripts/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
sass:
  sass_dir: assets/css
  style: compressed
exclude:
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - app
  - .idea
  - server.sh
  - LICENSE
